---
ららテラス武蔵小杉:
  id: 52ef1927498e945f59640219
  templates:
  - items: [ 0, 40 ]
    shops:
      url: "https://mitsui-shopping-park.com/lalat-musashikosugi/shopguide/?start={{item}}"
      selector: "ul.shop-guide-list-wrap li"
      attributes:
        listName:
          propertySelector: ".shop-name"
        listAddress:
          propertySelector: ".floor-num"
グランツリー武蔵小杉:
  id: 5361cba0498e5839aa495469
  shops:
  - url: "http://www.grand-tree.jp/web/shop/index.html"
    selector: "#shopList div.item:not(.all)"
    attributes:
      listName:
        propertySelector: .name
      listAddress:
        propertySelector: ".floor img"
        property:         alt
武蔵小杉東急スクエア:
  id: 50966024e4b0ad0d96424f52
  templates:
  - items: [ 1, 2, 3, 4, 5 ]
    shops:
      url: "http://www.kosugi-square.com/floor/?fcd={{item}}"
      selector: "div.floorlist__txt"
      attributes:
        listName:
          propertySelector: ".floorlist__txt--shopname"
        listAddress: "{{item}}F"
        listPhone:
          propertySelector: ".floorlist__txt--tel"
ヒカリエ:
  id: 4bd557cc6798ef3b4735638d
  subvenues:
    - 4f7f9ceae4b023c637e055ec
    - 4fa8cfe1e4b01db6889d52e1
    - 51722ef0e4b0cf8b85598a20
  templates:
  - items: [ 1, 2, 3, 4, 5 ]
    shops:
      url: "https://www.tokyu-dept.co.jp/shinqs/floor/{{item}}f.html"
      selector: "ul.shopList li"
      attributes:
        listName:
          propertySelector: "a"
        listAddress: "{{item}}F"
  - items: [ 6, 7, 8, 9, 11 ]
    shops:
      url: "http://www.hikarie.jp/floormap/{{item}}F.html"
      selector: "#floorshop .shopbox"
      attributes:
        listName:
          propertySelector: ".shoplogo"
        listAddress: "{{item}}F"
        listPhone:
          propertySelector: ".shop_info_m dd:nth-of-type(2), .shop_info_67_r dl:nth-of-type(3) dd"
  - items: [ b3, b2, b1 ]
    shops:
      url: "https://www.tokyu-dept.co.jp/shinqs/floor/{{item}}.html"
      selector: "ul.shopList li"
      attributes:
        listName:
          propertySelector: "a"
        listAddress: "{{upcasedItem}}F"
